# Stage 1: Build Angular
FROM node:20-bookworm-slim AS build
WORKDIR /app

# Copy Angular source
COPY client/package*.json ./
RUN npm ci

# Copy and build Angular
COPY client/ .
RUN npm run build



FROM nginx:alpine AS production

COPY client/nginx.conf /etc/nginx/nginx.conf
RUN cat /etc/nginx/nginx.conf
COPY --from=build /app/dist/client/ /usr/share/nginx/html/

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
