# Stage 1: Build Angular
FROM node:20-alpine AS build
WORKDIR /app

# Copy Angular source
COPY client/package*.json ./
RUN npm ci

# Copy and build Angular
COPY client/ .
RUN npm run build -- --configuration development

FROM nginx:alpine AS production

COPY client/nginx.dev.conf /etc/nginx/nginx.conf
COPY --from=build /app/dist/client/ /usr/share/nginx/html/

EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]
