# Stage 1: Build Angular
FROM node:20-alpine AS build
WORKDIR /app

# Copy Angular source
COPY client/package*.json ./
RUN npm ci

# Copy i build Angular
COPY client/ .
RUN npm run build

FROM nginx:alpine AS production

# 🔥 FIX: Kopiraj dist u nginx (NE API/wwwroot)
COPY --from=build /app/dist/client/ /usr/share/nginx/html/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
